/**
 * COBOL Comprehension Dashboard — Main Application
 *
 * Loads JSON data generated by the analysis scripts and renders
 * the dashboard panels: inventory, dependency graph, data lineage,
 * batch flows, dead code, and copybook tracing.
 */

(function () {
  "use strict";

  const DATA_DIR = "data";

  // ── Bootstrap ──────────────────────────────────────────────
  async function init() {
    try {
      const summary = await loadJSON("summary.json");
      if (!summary) return; // empty state stays visible

      document.getElementById("loading-state").style.display = "none";
      document.getElementById("dashboard").style.display = "block";

      renderSummaryCards(summary);
      setupTabs();

      // Load panel data in parallel
      const [inventory, depGraph, deadCode, lineage] = await Promise.all([
        loadJSON("inventory.json"),
        loadJSON("dependency_graph.json"),
        loadJSON("dead_code.json"),
        loadJSON("data_lineage.json"),
      ]);

      if (inventory) {
        renderProgramTable(inventory.programs);
        renderCopybookDetails(inventory.copybooks);
        renderBatchFlows(inventory.jcl_jobs);
      }
      if (depGraph) renderDependencyGraph(depGraph);
      if (deadCode) renderDeadCode(deadCode);
      if (lineage) renderLineage(lineage);
    } catch (err) {
      console.error("Dashboard init error:", err);
    }
  }

  async function loadJSON(filename) {
    try {
      const resp = await fetch(`${DATA_DIR}/${filename}`);
      if (!resp.ok) return null;
      return await resp.json();
    } catch {
      return null;
    }
  }

  // ── Tabs ───────────────────────────────────────────────────
  function setupTabs() {
    document.querySelectorAll(".tab").forEach((btn) => {
      btn.addEventListener("click", () => {
        document.querySelectorAll(".tab").forEach((b) => b.classList.remove("active"));
        document.querySelectorAll(".panel").forEach((p) => p.classList.remove("active"));
        btn.classList.add("active");
        document.getElementById("panel-" + btn.dataset.panel).classList.add("active");
      });
    });
  }

  // ── Summary Cards ─────────────────────────────────────────
  function renderSummaryCards(summary) {
    const inv = summary.inventory || {};
    const dep = summary.dependency_graph || {};
    const dead = summary.dead_code || {};
    const lin = summary.data_lineage || {};

    const cards = [
      { label: "Programs", value: inv.total_programs || 0, detail: `${inv.total_loc || 0} lines of code` },
      { label: "Copybooks", value: inv.total_copybooks || 0, detail: `${lin.shared_copybooks || 0} shared across programs` },
      { label: "JCL Jobs", value: inv.total_jcl_jobs || 0, detail: `${inv.programs_batch_only || 0} batch-only programs` },
      { label: "Dependencies", value: dep.total_edges || 0, detail: `${dep.total_nodes || 0} nodes in graph` },
      { label: "Dead Code", value: (dead.dead_programs || 0) + (dead.dead_copybooks || 0), detail: `${dead.dead_program_pct || 0}% of programs` },
      { label: "Data Flows", value: lin.total_flows || 0, detail: `${lin.datasets_mapped || 0} datasets mapped` },
    ];

    const container = document.getElementById("summary-cards");
    container.innerHTML = cards
      .map((c) => `<div class="card"><div class="label">${c.label}</div><div class="value">${c.value}</div><div class="detail">${c.detail}</div></div>`)
      .join("");
  }

  // ── Program Inventory ─────────────────────────────────────
  function renderProgramTable(programs) {
    const tbody = document.querySelector("#program-table tbody");
    tbody.innerHTML = programs
      .sort((a, b) => b.complexity_score - a.complexity_score)
      .map((p) => {
        const badge = p.complexity_score > 20 ? "high" : p.complexity_score > 10 ? "med" : "low";
        return `<tr>
          <td><strong>${esc(p.program_id)}</strong></td>
          <td>${p.loc}</td>
          <td><span class="badge badge-${badge}">${p.complexity_score}</span></td>
          <td>${p.copy_refs.length}</td>
          <td>${p.call_targets.length ? p.call_targets.map(esc).join(", ") : "&mdash;"}</td>
          <td>${p.cics_commands.length ? p.cics_commands.map(esc).join(", ") : "&mdash;"}</td>
        </tr>`;
      })
      .join("");
  }

  // ── Dependency Graph (D3 force-directed) ──────────────────
  function renderDependencyGraph(data) {
    const container = document.getElementById("dep-graph");
    const width = container.clientWidth || 900;
    const height = 550;

    const colorMap = {
      program: "#3b82f6",
      copybook: "#10b981",
      jcl_job: "#f59e0b",
      dataset: "#8b5cf6",
    };

    const svg = d3
      .select("#dep-graph")
      .append("svg")
      .attr("width", width)
      .attr("height", height)
      .attr("viewBox", [0, 0, width, height]);

    const g = svg.append("g");

    // Zoom
    svg.call(
      d3.zoom().scaleExtent([0.2, 5]).on("zoom", (e) => g.attr("transform", e.transform))
    );

    // Filter by checkbox state
    function getVisibleTypes() {
      const types = [];
      if (document.getElementById("show-programs").checked) types.push("program");
      if (document.getElementById("show-copybooks").checked) types.push("copybook");
      if (document.getElementById("show-jcl").checked) types.push("jcl_job");
      if (document.getElementById("show-datasets").checked) types.push("dataset");
      return types;
    }

    function render() {
      g.selectAll("*").remove();
      const visTypes = getVisibleTypes();
      const visNodeIds = new Set(data.nodes.filter((n) => visTypes.includes(n.type)).map((n) => n.id));
      const nodes = data.nodes.filter((n) => visNodeIds.has(n.id));
      const links = data.edges.filter((e) => visNodeIds.has(e.source) && visNodeIds.has(e.target));

      if (!nodes.length) return;

      const sim = d3
        .forceSimulation(nodes)
        .force("link", d3.forceLink(links).id((d) => d.id).distance(80))
        .force("charge", d3.forceManyBody().strength(-200))
        .force("center", d3.forceCenter(width / 2, height / 2))
        .force("collision", d3.forceCollide(25));

      const link = g
        .append("g")
        .selectAll("line")
        .data(links)
        .join("line")
        .attr("stroke", "#cbd5e1")
        .attr("stroke-width", 1.5)
        .attr("stroke-opacity", 0.6);

      const node = g
        .append("g")
        .selectAll("g")
        .data(nodes)
        .join("g")
        .call(d3.drag().on("start", dragstart).on("drag", dragged).on("end", dragend));

      node.append("circle").attr("r", 8).attr("fill", (d) => colorMap[d.type] || "#999");
      node
        .append("text")
        .text((d) => d.label)
        .attr("x", 12)
        .attr("y", 4)
        .attr("font-size", "10px")
        .attr("fill", "#334155");

      node.append("title").text((d) => `${d.type}: ${d.label}`);

      sim.on("tick", () => {
        link
          .attr("x1", (d) => d.source.x)
          .attr("y1", (d) => d.source.y)
          .attr("x2", (d) => d.target.x)
          .attr("y2", (d) => d.target.y);
        node.attr("transform", (d) => `translate(${d.x},${d.y})`);
      });

      function dragstart(event, d) {
        if (!event.active) sim.alphaTarget(0.3).restart();
        d.fx = d.x;
        d.fy = d.y;
      }
      function dragged(event, d) {
        d.fx = event.x;
        d.fy = event.y;
      }
      function dragend(event, d) {
        if (!event.active) sim.alphaTarget(0);
        d.fx = null;
        d.fy = null;
      }
    }

    render();
    document.querySelectorAll(".graph-controls input").forEach((cb) => cb.addEventListener("change", render));
  }

  // ── Dead Code ─────────────────────────────────────────────
  function renderDeadCode(data) {
    const s = data.summary || {};
    document.getElementById("dead-summary").innerHTML = `
      <div class="dead-stat"><div class="number">${s.dead_programs || 0}</div><div class="label">Dead Programs (${s.dead_program_pct || 0}%)</div></div>
      <div class="dead-stat"><div class="number">${s.dead_copybooks || 0}</div><div class="label">Dead Copybooks (${s.dead_copybook_pct || 0}%)</div></div>
    `;

    const progTbody = document.querySelector("#dead-programs-table tbody");
    progTbody.innerHTML = (data.dead_programs || [])
      .map((p) => `<tr><td>${esc(p.program_id)}</td><td>${p.loc}</td><td>${esc(p.reason)}</td></tr>`)
      .join("") || "<tr><td colspan='3'>No dead programs found</td></tr>";

    const cpyTbody = document.querySelector("#dead-copybooks-table tbody");
    cpyTbody.innerHTML = (data.dead_copybooks || [])
      .map((c) => `<tr><td>${esc(c.name)}</td><td>${c.field_count}</td><td>${c.total_bytes}</td><td>${esc(c.reason)}</td></tr>`)
      .join("") || "<tr><td colspan='4'>No dead copybooks found</td></tr>";
  }

  // ── Data Lineage ──────────────────────────────────────────
  function renderLineage(data) {
    const linTbody = document.querySelector("#lineage-table tbody");
    linTbody.innerHTML = (data.shared_copybooks || [])
      .sort((a, b) => b.sharing_count - a.sharing_count)
      .map((c) => `<tr><td><strong>${esc(c.copybook)}</strong></td><td>${c.sharing_count}</td><td>${c.used_by.map(esc).join(", ")}</td></tr>`)
      .join("");

    const ioTbody = document.querySelector("#fileio-table tbody");
    ioTbody.innerHTML = (data.file_io_map || [])
      .map((f) => `<tr><td>${esc(f.dataset)}</td><td>${f.read_by.map(esc).join(", ") || "&mdash;"}</td><td>${f.written_by.map(esc).join(", ") || "&mdash;"}</td></tr>`)
      .join("");
  }

  // ── Batch Flows ───────────────────────────────────────────
  function renderBatchFlows(jobs) {
    const container = document.getElementById("batch-flows");
    container.innerHTML = jobs
      .filter((j) => j.steps.length > 0)
      .map((j) => {
        const chain = j.steps
          .map((s) => `<span class="step-box" title="Step: ${esc(s.step_name)}">${esc(s.program)}</span>`)
          .join('<span class="step-arrow">&rarr;</span>');
        return `<div class="batch-card"><h4>${esc(j.job_name)}</h4><div class="step-chain">${chain}</div></div>`;
      })
      .join("") || "<p>No batch jobs with steps found.</p>";
  }

  // ── Copybook Tracing ──────────────────────────────────────
  function renderCopybookDetails(copybooks) {
    const container = document.getElementById("copybook-details");
    container.innerHTML = copybooks
      .filter((c) => c.fields.length > 0)
      .sort((a, b) => b.fields.length - a.fields.length)
      .slice(0, 20) // Show top 20
      .map((c) => {
        const fields = c.fields
          .filter((f) => !f.is_condition)
          .map((f) => `<div>${String(f.level).padStart(2, "0")}</div><div>${esc(f.name)}</div><div>${esc(f.picture || "GROUP")}</div><div>${f.byte_size}B @${f.byte_offset}</div>`)
          .join("");
        return `<div class="copybook-card">
          <h4>${esc(c.name)} <span style="font-weight:400;color:#64748b;">(${c.total_bytes} bytes, ${c.fields.length} fields)</span></h4>
          <div class="field-grid">
            <div class="fh">Lvl</div><div class="fh">Field Name</div><div class="fh">PIC</div><div class="fh">Size</div>
            ${fields}
          </div>
        </div>`;
      })
      .join("");
  }

  // ── Utility ───────────────────────────────────────────────
  function esc(s) {
    if (!s) return "";
    const el = document.createElement("span");
    el.textContent = String(s);
    return el.innerHTML;
  }

  // ── Launch ────────────────────────────────────────────────
  document.addEventListener("DOMContentLoaded", init);
})();
